/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type TransferCompleted = ContractEventLog<{
  sender: string;
  value: string;
  0: string;
  1: string;
}>;

export interface MultiSender extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MultiSender;
  clone(): MultiSender;
  methods: {
    owner(): NonPayableTransactionObject<string>;

    multisend(to: string[]): PayableTransactionObject<void>;
  };
  events: {
    TransferCompleted(cb?: Callback<TransferCompleted>): EventEmitter;
    TransferCompleted(
      options?: EventOptions,
      cb?: Callback<TransferCompleted>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "TransferCompleted", cb: Callback<TransferCompleted>): void;
  once(
    event: "TransferCompleted",
    options: EventOptions,
    cb: Callback<TransferCompleted>
  ): void;
}
